config/routes.rb
Rails.application.routes.draw do

  resources :articles, except: [:delete]

  delete "articles/:id",      to: "articles#destroy", as: :article_destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end # -> views -> folder with name of the controller -> template with name of action

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @articles = Article.find(params[:id])
  end

  def update
    @article = Article.new
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="navbar-wagon">
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="" class="navbar-wagon-item navbar-wagon-link"><%= link_to "Write New Article", new_article_path %> </a>
  </div>
</div>
<%= form_for(@articles) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<div class="navbar-wagon">
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="" class="navbar-wagon-item navbar-wagon-link"><%= link_to "Write New Article", new_article_path %> </a>
  </div>
</div>
<h1>Welcome on NewsWeb</h1>


<ul>
<% @articles.each do |articl| %>
<li><%= link_to articl.title, article_path(articl)%></li>
<% end %>

</ul>

app/views/articles/new.html.erb
<div class="navbar-wagon">
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="" class="navbar-wagon-item navbar-wagon-link"><%= link_to "Write New Article", new_article_path %> </a>
  </div>
</div>
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<div class="navbar-wagon">
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="" class="navbar-wagon-item navbar-wagon-link"><%= link_to "Write New Article", new_article_path %> </a>
  </div>
</div>
<h1>TITLE <%= @article.title %> <%= link_to "edit article", edit_article_path %> <%= link_to "delete article", article_destroy_path, method: :delete %></h1>
<h1>CONTENT <%= @article.content %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>
  </body>
</html>